feat: restaurant menu
Fannolo/whizzer pull request #4
Opened 2022-07-02 21:43 UTC by devteapot

2022-07-04 07:38 UTC, LRNZ09 requested changes

2022-07-04 07:38 UTC, LRNZ09 commented on whizzer/features/menu/components/CategoriesSlider/CategoriesSlider.tsx
> +        return (
Make a dedicated component for the item

2022-07-04 07:38 UTC, LRNZ09 commented on whizzer/features/menu/components/CategoriesSlider/CategoriesSlider.tsx
> +      renderItem={({ item, index }) => {
Make a named function for the render item callback

2022-07-04 07:38 UTC, LRNZ09 commented on whizzer/features/menu/screens/DishDetailScreen/DishDetailScreen.tsx
> +const DishDetailScreen: React.FC<DishDetailScreenProps> = ({ route }) => {
Do not use React.FC

2022-07-04 07:38 UTC, LRNZ09 commented on whizzer/features/menu/screens/RestaurantMenu/RestaurantMenu.tsx
> +const RestaurantMenuScreen: React.FC<RestaurantMenuScreenProps> = ({ navigation }) => {
Do not use React.FC

2022-07-07 07:28 UTC, devteapot commented on whizzer/features/menu/screens/RestaurantMenu/RestaurantMenu.tsx
> +      .filter("restaurant_id", "in", `(${restaurantId})`) // TODO: check is condition
We could try to filter like this
```suggestion
      .is("restaurant_id", restaurantId)
```

2022-07-31 14:41 UTC, Fannolo approved these changes

2022-07-31 14:42 UTC, merged