feat: home screen
Fannolo/whizzer pull request #5
Opened 2022-07-03 11:24 UTC by Fannolo

2022-07-04 07:24 UTC, LRNZ09 commented on whizzer/features/common/components/Carousel/Carousel.tsx
> +      <ScrollView horizontal {...rest}>
Use `FlatList` instead

2022-07-04 07:30 UTC, LRNZ09 requested changes

2022-07-04 07:30 UTC, LRNZ09 commented on whizzer/features/menu/components/CategoriesSlider/CategoriesSlider.tsx
> +type Props = {};
Needless type

2022-07-04 20:14 UTC, Fannolo commented on whizzer/features/home/components/RestaurantCard/RestaurantCard.tsx
> +          navigation.navigate(RootScreenNames.RestaurantMenuScreen)
never!

2022-07-04 20:14 UTC, Fannolo commented on whizzer/features/common/components/Carousel/Carousel.tsx
> +      <ScrollView horizontal {...rest}>
Never!

2022-07-07 07:36 UTC, devteapot commented on whizzer/.env
> +SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFieXdjcXF1a3NmcGFpcGpvemJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NTY3NTM2MTIsImV4cCI6MTk3MjMyOTYxMn0.jvT4I8oW07U_geuo
Should't push this file

2022-07-07 17:59 UTC, Fannolo commented on whizzer/.env
> +SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFieXdjcXF1a3NmcGFpcGpvemJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NTY3NTM2MTIsImV4cCI6MTk3MjMyOTYxMn0.jvT4I8oW07U_geuo
whooo says that

2022-07-07 18:01 UTC, devteapot commented on whizzer/.env
> +SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFieXdjcXF1a3NmcGFpcGpvemJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NTY3NTM2MTIsImV4cCI6MTk3MjMyOTYxMn0.jvT4I8oW07U_geuo
god

2022-07-07 20:32 UTC, LRNZ09 commented on whizzer/features/home/components/RestaurantCard/RestaurantCard.tsx
> +            <Text>69km</Text>
Should it show the `item.distance`?

2022-07-07 20:34 UTC, LRNZ09 commented on whizzer/navigation/header/HomeScreenHeader/HomeScreenHeader.test.tsx
> +  it("should render the home screen header", () => {});
Add a real test or just use `it.todo`

2022-07-08 11:26 UTC, Fannolo commented on whizzer/features/home/components/RestaurantCard/RestaurantCard.tsx
>              source={require("../../../../assets/images/sushi_restaurant_cover.jpeg")}
we are working on it in the restaurant menu MR

2022-07-08 11:26 UTC, Fannolo commented on whizzer/features/home/components/RestaurantCard/RestaurantCard.tsx
> +            <Text>69km</Text>
working on the other MR

2022-07-08 18:14 UTC, merged