feat: create nfc reader for the restaurant
Fannolo/whizzer pull request #7
Opened 2022-07-10 15:18 UTC by Fannolo

2022-08-23 23:56 UTC, devteapot requested changes

2022-08-23 23:56 UTC, devteapot commented on whizzer/features/dev/screens/WriteNFCTags/WriteNFCTags.tsx
> +  }
In this function we could just return true at the end and return false in the catch block and we can avoid declaring the result variable.

2022-08-23 23:56 UTC, devteapot commented on whizzer/features/home/screens/HomeScreen.tsx
> +  };
We should group these functions that use the NFC library in their own folder

2022-08-23 23:56 UTC, devteapot commented on whizzer/features/menu/screens/RestaurantMenu/RestaurantMenu.tsx
> +  }
This is a previous version of the function defined in `HomeScreen` it should be removed

2022-08-23 23:56 UTC, devteapot commented on whizzer/features/menu/screens/RestaurantMenu/RestaurantMenu.tsx
> +      </TouchableOpacity>
We should also remove this since we are scanning the NFC to get to this page

2022-08-23 23:56 UTC, devteapot commented on whizzer/navigation/LinkingConfiguration.ts
> +      Modal: "modal",
The key `Modal` is not valid for `RootStackParamList`, this entry should be deleted

2022-08-24 10:29 UTC, Fannolo commented on whizzer/features/dev/screens/WriteNFCTags/WriteNFCTags.tsx
> +  }
好的

2022-08-24 10:29 UTC, Fannolo commented on whizzer/features/home/screens/HomeScreen.tsx
> +  };
好的

2022-08-24 10:29 UTC, Fannolo commented on whizzer/features/menu/screens/RestaurantMenu/RestaurantMenu.tsx
> +      </TouchableOpacity>
好的

2022-08-24 12:01 UTC, devteapot commented on whizzer/features/dev/screens/WriteNFCTags/WriteNFCTags.tsx
> +  }
감사합니다

2022-08-24 12:01 UTC, devteapot commented on whizzer/features/home/screens/HomeScreen.tsx
> +  };
감사합니다

2022-08-24 12:01 UTC, devteapot commented on whizzer/features/menu/screens/RestaurantMenu/RestaurantMenu.tsx
> +      </TouchableOpacity>
감사합니다

2022-08-24 12:05 UTC, devteapot approved these changes

2022-08-24 12:08 UTC, merged